
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/cicd-circleci

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      
      - add_ssh_keys:
          fingerprints:
            - "04:82:e0:55:70:73:62:e5:d2:37:5b:9c:05:d9:74:a3"
      - run: yarn 
      - run: yarn build
      - run: git checkout gh-pages
      - run: git pull
      - run: cp -R build/* .
      - run: sed -i -e 's/static/a-nice-react-notebook\/static/g' index.html
      - run: sed -i -e 's/manifest/a-nice-react-notebook\/manifest/g' index.html
      - run: sed -i -e 's/favicon/a-nice-react-notebook\/favicon/g' index.html
      - run: cat index.html
      - run: git add .
      - run: git commit -m "Update GHPage"
      - run: git push origin gh-pages
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
